// <auto-generated />
using FamAppAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamAppAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240122134915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FamAppAPI.Models.Groups", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("premium")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("FamAppAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FamAppAPI.Models.UserInGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UsersInGroups");
                });

            modelBuilder.Entity("FamAppAPI.Models.UserInGroup", b =>
                {
                    b.HasOne("FamAppAPI.Models.Groups", "Groups")
                        .WithMany("UsersInGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamAppAPI.Models.User", "Users")
                        .WithMany("UsersInGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groups");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FamAppAPI.Models.Groups", b =>
                {
                    b.Navigation("UsersInGroups");
                });

            modelBuilder.Entity("FamAppAPI.Models.User", b =>
                {
                    b.Navigation("UsersInGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
